### ISSUE TITLE
Proposals for global installation

### ISSUE THREAD

**Issue by Firef0x** [dohliam/forvocl#3]
Hello @dohliam ,

Appreciate your great job! Simply speaking, would you pls make `forvocl` work like what we have discussed in https://github.com/dohliam/gdcl/issues/2 ?

Hope for your reply!

Yours sincerely! :bow:

**Comment by dohliam** [comment]
Good idea. I was meaning to do this at some point anyway. I'll fix it and also add something so that it checks in `~/.config/gdcl` if `~/.config/forvocl` and the `xdg` directories don't exist (so that we don't have to have two directories with the same information if we use both programs).
